/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as attestors from "./attestors";
export type { attestors };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { BadgerCore } from "./BadgerCore";
export type { TrustSigil } from "./TrustSigil";
