/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITrustAttestor,
  ITrustAttestorInterface,
} from "../../../contracts/interfaces/ITrustAttestor";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "attestMint",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITrustAttestor__factory {
  static readonly abi = _abi;
  static createInterface(): ITrustAttestorInterface {
    return new utils.Interface(_abi) as ITrustAttestorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITrustAttestor {
    return new Contract(address, _abi, signerOrProvider) as ITrustAttestor;
  }
}
