/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface OrbisBridgeInterface extends utils.Interface {
  functions: {
    "attestMint(address,address,bytes)": FunctionFragment;
    "litActionPkp()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "attestMint" | "litActionPkp"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "attestMint",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "litActionPkp",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "attestMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "litActionPkp",
    data: BytesLike
  ): Result;

  events: {};
}

export interface OrbisBridge extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OrbisBridgeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    attestMint(
      sender: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    litActionPkp(overrides?: CallOverrides): Promise<[string]>;
  };

  attestMint(
    sender: PromiseOrValue<string>,
    recipient: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  litActionPkp(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    attestMint(
      sender: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    litActionPkp(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    attestMint(
      sender: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    litActionPkp(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    attestMint(
      sender: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    litActionPkp(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
